### ISSUE TITLE
SRT Stats HUD is connected to the game, but doesn't display info

### ISSUE THREAD

**Issue by czy4rn1** [SpeedrunTooling/StatsHUD#14]
As said in the title, the in-game Overlay of SRT works fine and exactly how it should. It displays current In-game time, for example "IGT: 00:09:45" and player's HP "Leon: 1200 / 1200".

RE2R: The SRT Stats HUD, the website version with UI JSON installed only displays "IGT: undefined", despite having the game open and running. It says that the IGT is undefined, so it is connected to the game. When the game isn't running the site is full black as it should.

RE4R: Everything it displays is undefined. IGT: undefined, HP as undefined / undefined and so on. 

This issue concerns Resident Evil 2 Remake and Resident Evil 4 Remake and probably other games.

**Comment by VideoGameRoulette** [comment]
that means you are using the incorrect version for the website, we have 2 websites one for legacy patches and one for latest release this is not an issue its expected behavior.

**Comment by czy4rn1** [comment]
I'm not sure I understand. I followed all the steps in the description and the guide video to correctly install SRT Plugin Manager and the SRT Host, everything is up to date, including the UI JSON and the STATS HUD website pulled exactly from the SRT Plugin Manager app doesn't work for me. Just IGT: undefined
